# Moje první analýza

Tento notebook procvičuje práci s Jupyter Notebooky, numpy a matplotlib.

In [1]:
import numpy as np

data = np.load("pacienti.npy")
print("Tvar pole:", data.shape)
print("Prvních 5 řádků:\n", data[:5])
print("-" * 40)

prumery = np.mean(data, axis=0)
odchylky = np.std(data, axis=0)

print("Průměr každého ukazatele:\n", prumery)
print("Směrodatná odchylka každého ukazatele:\n", odchylky)
print("-" * 40)

maska_hypertenze = data[:, 0] >= 140
pacienti_hypertenze = data[maska_hypertenze]

pocet_hypertoniku = len(pacienti_hypertenze)
prumerny_systolicky_hypertoniku = np.mean(pacienti_hypertenze[:, 0])

print("Počet pacientů s hypertenzí:", pocet_hypertoniku)
print("Průměrný systolický tlak těchto pacientů:", prumerny_systolicky_hypertoniku)
print("-" * 40)

pulzni_tlak = data[:, 0] - data[:, 1]
data = np.column_stack((data, pulzni_tlak))

print("Tvar nového pole (po přidání 4. sloupce):", data.shape)
print("Ukázka prvních 3 řádků po úpravě:\n", data[:3])
print("-" * 40)

index_nejvyssi_tep = np.argmax(data[:, 2])
zaznam_pacienta = data[index_nejvyssi_tep]

print("Index pacienta s nejvyšší tepovou frekvencí:", index_nejvyssi_tep)
print("Celý záznam pacienta:\n", zaznam_pacienta)

Tvar pole: (20, 3)
Prvních 5 řádků:
 [[129.6  78.2  93. ]
 [109.4  73.2  72. ]
 [136.3  92.2  61. ]
 [139.1  78.5  89. ]
 [ 95.7  75.7  80. ]]
----------------------------------------
Průměr každého ukazatele:
 [124.51   81.105  77.   ]
Směrodatná odchylka každého ukazatele:
 [12.72807527  7.73869983 11.28273017]
----------------------------------------
Počet pacientů s hypertenzí: 1
Průměrný systolický tlak těchto pacientů: 141.9
----------------------------------------
Tvar nového pole (po přidání 4. sloupce): (20, 4)
Ukázka prvních 3 řádků po úpravě:
 [[129.6  78.2  93.   51.4]
 [109.4  73.2  72.   36.2]
 [136.3  92.2  61.   44.1]]
----------------------------------------
Index pacienta s nejvyšší tepovou frekvencí: 0
Celý záznam pacienta:
 [129.6  78.2  93.   51.4]
